### PR TITLE
Mirage compatibility by splitting off Unix-dependent functionality

### LINKED ISSUE #17: Split out Unix-specific code to support MirageOS better
This is a proposal to split out the Unix-specific function calls to a `imagelib.unix` package, to enable use (well, linking) on MirageOS.

I have not had too many issues since I mainly use MirageOS on Xen, which doesn't seem to do *eager relocations,* but @hannesm mentioned that this is a problem on some of the other backends.

In any case the problem is that functions like `Sys.remove`, `Sys.command`, `Unix.create_process`, [...] are not available in MirageOS, and calling them causes the application to crash.

### LINKED ISSUE #18: Port to last version of the `decompress` library
see https://github.com/ocaml/opam-repository/pull/12313.

### LINKED ISSUE #21: Seems something is broken with last version of decompress
If I try to compile a file `test.ml` containing
```ocaml
let _ = ImageLib.openfile
```
the following, using the command
```bash
ocamlfind ocamlopt -package imagelib -linkpkg -o test test.ml
```
I get the following error.
```bash
File "test.ml", line 1:
Error: No implementations provided for the following modules:
         Checkseum referenced from /home/rodolphe/.opam/4.05.0/lib/decompress/impl/decompress_impl.cmxa(Decompress_impl__Decompress_safe),
           /home/rodolphe/.opam/4.05.0/lib/decompress/impl/decompress_impl.cmxa(Decompress_impl)
         ImageChannels referenced from /home/rodolphe/.opam/4.05.0/lib/imagelib/imagelib.cmxa(ImagePNG)
```

### PR DESCRIPTION
**Pull request by cfcs**
This implements Unix-dependent helpers, and introduces a `chunk_writer` for implementation-independent output.

ping @rlepigre @rymdhund

EDIT: Also fixes #18  fixes #17 fixes #21

### CODE REVIEW

File: unix/imageUtil_unix.ml [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+  close_in ich; ls
+
+let chunk_reader_of_in_channel ich : chunk_reader =
+  function
+  | `Bytes num_bytes ->
+    begin try Ok (really_input_string ich num_bytes)
+      with
+      | End_of_file ->
+        let offset = pos_in ich in
+        close_in ich ;
```
Comment (rymdhund) [inline unix/imageUtil_unix.ml:64]: Do we really want to close the in_channel here? Shouldn't it be the responsibility of the creator of the chunk_reader to call close on it?

And if we do want to close the channel, we probably want the close_in_noerr here

File: unix/imageUtil_unix.ml [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+        raise e
+    end
+  | `Close -> close_in ich; Ok ""
+
+
+let chunk_writer_of_out_channel och : chunk_writer =
+  function
+  | `String x ->
+    ( try Ok (output_string och x) with
+      | _ -> close_out och; Error `Write_error)
```
Comment (rymdhund) [inline unix/imageUtil_unix.ml:77]: same as with the close_in above

**Review by rymdhund — COMMENTED** [review]
I think this looks like a nice way to split the core from the unix stuff

**Comment by rlepigre** [comment]
Sorry, I'm really busy currently, so I probably won't be able to have a proper look until the weekend.
