### PR TITLE
try to fix alpha handling for GIF and resizing

### LINKED ISSUE #42: Incomplete support for alpha channel in the GIF format.
I'm reading a PNG or GIF (see attached files) with imagelib, and saving the image in png (I am using Cairo that can only
read png files) but the resulting png file loses the alpha property. The image background is not transparent anymore.

Here is the code I'm using to read the png or GIF:
```
let png_file_of_url url =
  let image = 
    (* ImageLib_unix.openfile url  *)
    let fn = url in
    let ich = ImageUtil_unix.chunk_reader_of_path fn in
    let extension = ImageUtil_unix.get_extension' fn in
    pr2 "reading";
    try ImageLib.openfile ~extension ich 
    with Image.Not_yet_implemented _ -> failwith (spf "PB with %s" fn)
  in
  let tmpfile = 
    (*Filename.temp_file "imagelib" ".png" 
    *) "/tmp/imagelib.png" in
  pr2 "saving";
  ImageLib_unix.writefile tmpfile image;
  tmpfile
```

### PR DESCRIPTION
**Pull request by cfcs**
This PR aims to fix https://github.com/rlepigre/ocaml-imagelib/issues/42 by adding alpha channel handling for the cubic interpolation resizing, and making the GIF reader default to transparent images.

It is possible this in turn will break GIFs that define a background color (but do not use transparency).
I did not have such a GIF lying around, so I was unable to test that.

### CODE REVIEW

**Comment by cfcs** [comment]
I also implemented an option for selecting specific frames from multi-frame formats (currently only GIF) to imagetool, and put a small section about `imagetool` in the README.

**Comment by cfcs** [comment]
@rlepigre If you're OK with these changes we can merge, and then we should probably do a release to get the transparency patches in there :-)

File: app/imagetool.ml [hunk 1]
```diff
@@ -119,7 +156,7 @@ let () =
   let handle_resize input_img =
     let doit x y =
       let x, y = max 1 x, max 1 y in
-      let dst = Image.create_rgb ~alpha:false x y in
+      let dst = Image.create_rgb ~alpha:true x y in
```
Comment (rlepigre) [inline app/imagetool.ml]: Should't we only create an alpha channel if the `input_img` has one here?

**Review by rlepigre — COMMENTED** [review]
Thanks!

File: app/imagetool.ml (hunk 1 above)
Comment (cfcs) [reply app/imagetool.ml]: You're right, I was skipping corners.

**Comment by cfcs** [comment]
I updated it to address your comment @rlepigre. It's still not quite right; for the terminal display of animated GIFs it handles transparent frames (on top of the original non-transparent background) poorly by painting over it rather than skipping the output of those, but I do not have time to fix that now. It does however paint the turtle.gif correctly I believe :)

**Review by rlepigre — APPROVED** [review]
Looks good to me, feel free to merge. And thanks a lot!
